# To change this license header, choose License Headers in Project Properties.
# To change this template file, choose Tools | Templates
# and open the template in the editor.
FROM payara/server-full:5.193.1
COPY target/HelloApp-1.0.war $DEPLOY_DIR